#!/usr/bin/env python3
"""COCO -> YOLO segmentation label conversion with D028 split routing (O005).

Path B (in-place conversion). Single source of truth is the SemanticBLT COCO
JSON; YOLO labels are derived. Parameterised by class-collapse rule so the same
script serves Phase B (binary) and Phase C (multiclass, trunk/pole distinct).

Pipeline:
  1. Run ultralytics `convert_coco()` once over the three source COCO JSONs
     (use_segments=True, cls91to80=False). It emits one YOLO txt per image with
     `class = category_id - 1` and normalised polygon segments.
  2. Collapse: keep only foreground COCO categories (per the mode's map), rewrite
     their class to the collapsed target id, drop everything else.
  3. Route each frame into data/<out>/{images,labels}/{train,val,test}/ per the
     D028 manifest. Consumption rule (D028): train = all frames; val/test =
     representative frames only. Manifest split `valid` -> ultralytics `val/`.
  4. Emit canopy_state_map.json (for stratified evaluation) and the data.yaml.

Deterministic: frames processed in sorted filename order; convert_coco is
deterministic. No training here.
"""

from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List

from ultralytics.data.converter import convert_coco

SOURCE_SPLITS = ("train", "valid", "test")          # original COCO folders
SPLIT_TO_YOLO_DIR = {"train": "train", "valid": "val", "test": "test"}
COCO_ANN = "_annotations.coco.json"

# Class-collapse modes. Keys are COCO category_ids; values are YOLO class ids.
# COCO cats: 3 = pole, 5 = trunk (verified against the export / D006).
MODES: Dict[str, dict] = {
    "binary": {
        "collapse": {3: 0, 5: 0},                   # pole + trunk -> single class
        "names": {0: "crop"},
        "out_subdir": "data/yolo_binary",
        "data_yaml": "configs/phase_b_yolo_binary_data.yaml",
    },
    "multiclass": {
        "collapse": {5: 0, 3: 1},                   # trunk -> 0, pole -> 1 (D025 / PHASE_C_SPEC 4.1)
        "names": {0: "trunk", 1: "pole"},
        "out_subdir": "data/yolo_multiclass",
        "data_yaml": "configs/phase_c_yolo_multiclass_data.yaml",
    },
}


def frames_to_place(manifest: dict) -> List[dict]:
    """Rows to materialise: all train frames + representative val/test frames (D028)."""
    return [r for r in manifest["images"]
            if r["split"] == "train" or r["is_representative"]]


def run_convert_coco(coco_root: Path, workdir: Path) -> Path:
    """Run convert_coco over the three source JSONs; return the labels root.

    Copies each source folder's `_annotations.coco.json` into one input dir under
    distinct names (train/valid/test.json) so their outputs land in separate
    subfolders (the source files otherwise share a name)."""
    in_dir = workdir / "in"
    in_dir.mkdir(parents=True)
    for s in SOURCE_SPLITS:
        shutil.copy(coco_root / s / COCO_ANN, in_dir / f"{s}.json")
    out_dir = workdir / "out"
    convert_coco(str(in_dir), save_dir=str(out_dir),
                 use_segments=True, use_keypoints=False, cls91to80=False)
    return out_dir / "labels"                        # out/labels/<source_split>/<stem>.txt


def collapse_lines(raw_path: Path, collapse: Dict[int, int]) -> List[str]:
    """Keep only foreground classes, rewrite to the collapsed target id.

    convert_coco wrote `class = category_id - 1`, so category_id = raw_class + 1.
    """
    lines: List[str] = []
    if raw_path.exists():
        for ln in raw_path.read_text().splitlines():
            ln = ln.strip()
            if not ln:
                continue
            parts = ln.split()
            category_id = int(parts[0]) + 1
            if category_id in collapse:
                lines.append(" ".join([str(collapse[category_id])] + parts[1:]))
    return lines


def count_expected_foreground(coco_root: Path, place_by_orig: Dict[str, set],
                              collapse: Dict[int, int]) -> int:
    """Ground-truth count of foreground annotations for placed frames, read
    straight from the COCO JSONs — an independent audit of the YOLO line count."""
    total = 0
    fg_cats = set(collapse)
    for s in SOURCE_SPLITS:
        coco = json.loads((coco_root / s / COCO_ANN).read_text())
        id_to_name = {im["id"]: im["file_name"] for im in coco["images"]}
        placed = place_by_orig.get(s, set())
        for a in coco["annotations"]:
            if a["category_id"] in fg_cats and id_to_name[a["image_id"]] in placed:
                total += 1
    return total


def write_data_yaml(repo: Path, out_root: Path, mode: dict) -> Path:
    names_block = "\n".join(f"  {k}: {v}" for k, v in mode["names"].items())
    yaml_text = (
        "# ultralytics data configuration (generated by scripts/coco_to_yolo.py, O005)\n"
        f"path: {out_root.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "test: images/test\n\n"
        f"nc: {len(mode['names'])}\n"
        "names:\n"
        f"{names_block}\n"
    )
    path = repo / mode["data_yaml"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml_text)
    return path


def verify(out_root: Path, collapse: Dict[int, int], n_expected_fg: int) -> dict:
    """Assert acceptance criteria (§4.5): valid classes, coords in [0,1], counts."""
    valid_classes = set(collapse.values())
    n_lines = 0
    n_labels = 0
    for txt in (out_root / "labels").rglob("*.txt"):
        n_labels += 1
        for ln in txt.read_text().splitlines():
            ln = ln.strip()
            if not ln:
                continue
            parts = ln.split()
            cls = int(parts[0])
            coords = [float(x) for x in parts[1:]]
            assert cls in valid_classes, f"unexpected class {cls} in {txt}"
            assert len(coords) >= 6 and len(coords) % 2 == 0, f"bad polygon in {txt}"
            assert all(0.0 <= c <= 1.0 for c in coords), f"coord out of [0,1] in {txt}"
            n_lines += 1
    assert n_lines == n_expected_fg, (
        f"foreground line count {n_lines} != expected {n_expected_fg} from COCO")
    return {"label_files": n_labels, "foreground_lines": n_lines}


def main() -> None:
    ap = argparse.ArgumentParser(description="COCO->YOLO conversion with D028 routing (O005).")
    ap.add_argument("--coco-root",
                    default="/workspaces/dissertation/SemanticBLT.v1-2024-june.coco-segmentation")
    ap.add_argument("--manifest",
                    default="/workspaces/dissertation/vineyard_nav/data/splits/resplit_70_20_10.json")
    ap.add_argument("--repo", default="/workspaces/dissertation/vineyard_nav")
    ap.add_argument("--mode", default="binary", choices=list(MODES))
    ap.add_argument("--link", choices=["symlink", "copy"], default="symlink")
    args = ap.parse_args()

    coco_root = Path(args.coco_root)
    repo = Path(args.repo)
    mode = MODES[args.mode]
    collapse = mode["collapse"]
    manifest = json.loads(Path(args.manifest).read_text())
    out_root = repo / mode["out_subdir"]

    # Fresh output tree (we own data/yolo_binary).
    for sub in ("images", "labels"):
        shutil.rmtree(out_root / sub, ignore_errors=True)
        for d in ("train", "val", "test"):
            (out_root / sub / d).mkdir(parents=True, exist_ok=True)

    rows = sorted(frames_to_place(manifest), key=lambda r: r["filename"])
    place_by_orig: Dict[str, set] = defaultdict(set)
    for r in rows:
        place_by_orig[r["orig_split"]].add(r["filename"])

    workdir = Path(tempfile.mkdtemp(prefix="coco2yolo_"))
    try:
        raw_root = run_convert_coco(coco_root, workdir)

        canopy_map: Dict[str, str] = {}
        stats = defaultdict(lambda: defaultdict(int))     # yolo_split -> canopy -> count
        empty_labels = 0
        for r in rows:
            fn = r["filename"]
            stem = Path(fn).stem
            yolo_split = SPLIT_TO_YOLO_DIR[r["split"]]
            lines = collapse_lines(raw_root / r["orig_split"] / f"{stem}.txt", collapse)

            label_path = out_root / "labels" / yolo_split / f"{stem}.txt"
            label_path.write_text(("\n".join(lines) + "\n") if lines else "")
            if not lines:
                empty_labels += 1

            dst = out_root / "images" / yolo_split / fn
            src = coco_root / r["orig_split"] / fn
            if dst.exists() or dst.is_symlink():
                dst.unlink()
            if args.link == "symlink":
                dst.symlink_to(src.resolve())
            else:
                shutil.copy(src, dst)

            canopy_map[fn] = r["canopy_state"]
            stats[yolo_split][r["canopy_state"]] += 1

        (out_root / "canopy_state_map.json").write_text(
            json.dumps(canopy_map, indent=2, sort_keys=True))
        data_yaml = write_data_yaml(repo, out_root, mode)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    n_expected_fg = count_expected_foreground(coco_root, place_by_orig, collapse)
    v = verify(out_root, collapse, n_expected_fg)

    # --- report ---
    print(f"COCO->YOLO conversion complete (mode={args.mode}, link={args.link})")
    print(f"  out: {out_root}")
    print(f"  data.yaml: {data_yaml}")
    print(f"  classes: {mode['names']}")
    print("  frames placed per split (canopy):")
    for ys in ("train", "val", "test"):
        bv, cp = stats[ys]["bare_vine"], stats[ys]["canopy"]
        print(f"    {ys:<5} bare_vine={bv:<4} canopy={cp:<4} total={bv + cp}")
    print(f"  label files: {v['label_files']}  (empty/background: {empty_labels})")
    print(f"  foreground polygon lines: {v['foreground_lines']} "
          f"(== COCO cat{sorted(collapse)} count for placed frames ✓)")
    print(f"  canopy_state_map.json entries: {len(canopy_map)}")


if __name__ == "__main__":
    main()
